# Generated by Django 5.2.4 on 2025-09-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stop_alter_busroute_name_remove_busroute_stops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='driver',
        ),
    ]
