# Generated by Django 5.2.4 on 2025-09-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='core.busroute'),
        ),
    ]
