# Generated by Django 5.2.7 on 2025-10-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_emailotp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routestop",
            name="distance_along_route_m",
        ),
        migrations.AddField(
            model_name="routestop",
            name="distance_to_next_m",
            field=models.FloatField(
                blank=True,
                help_text="Distance in meters from this stop to the next stop in route",
                null=True,
            ),
        ),
    ]
