# Generated by Django 5.2.7 on 2025-10-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_routestop_distance_along_route_m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="busroute",
            name="reverse_route",
            field=models.ForeignKey(
                blank=True,
                help_text="The reverse direction of this route",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forward_route",
                to="core.busroute",
            ),
        ),
    ]
